#!/bin/bash
pkg=$1

curl -LO https://raw.githubusercontent.com/RhinoCodes/repo/main/repo/$1/semcfile >> /dev/null
curl -LO https://raw.githubusercontent.com/RhinoCodes/repo/main/repo/$1/deps >> /dev/null
echo
echo Name
cat deps
echo $1
echo 
read -p "Do you want to continue? [Y/n] " answer

if [ -x ${answer} ]
then
	answer="y"
fi


if [ ${answer,,} == "y" ]
then
	source semcfile
	mkdir bindir/$1
	cd builddir/
	fetch >> /dev/null
	cd $1
	install
	cd ..
	rm -rf $1
	cd ..
	chmod -R +x bindir/$1/
	cd bin
	ln -s ../bindir/$1/* .
	cd ..
	rm -rf builddir/$1
	while read line; do ./install_quiet $line; done < deps
fi
