#!/bin/bash
pkg=$1

curl -LO https://raw.githubusercontent.com/RhinoCodes/repo/main/repo/$1/semcfile >> /dev/null
curl -LO https://raw.githubusercontent.com/RhinoCodes/repo/main/repo/$1/deps >> /dev/null
echo
echo Name
cat deps
echo $1
echo 
read -p "Do you want to continue? [Y/n] " answer

if [ -x ${answer} ]
then
	answer="y"
fi


if [ ${answer,,} == "y" ]
then
	./install_quiet $pkg >> /dev/null
fi
