#!/bin/bash

#!/bin/bash
pkg=$1

echo
echo Name
echo $1
echo
read -p "Do you want to continue? [Y/n] " answer

if [ -x ${answer} ]
then
	answer="y"
fi


if [ ${answer,,} == "y" ]
then
	rm -rf bindir/$1
	find bin/ -xtype l -delete
fi
